language: generic
sudo: required

services:
  - docker

notifications:
  on_success: never
  on_failure: always

matrix:
  include:
    - language: generic
      before_script:
        - sudo apt-get -y install netcat
      script:
        - cd 3.3/
        - docker build -t pe46dro/teamspeak3-docker-image .
